name: Release Automático

on:
  push:
    branches:
      - main

permissions:
  contents: write # Dá permissão pro robô commitar de volta
  issues: write
  pull-requests: write

jobs:
  release:
    name: Gerar Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para ler todo o histórico de commits

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Rodar Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release