name: Mark stale issues and PRs

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Stale action
      uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        # Issue settings
        stale-issue-message: 'Esta issue está inativa há 60 dias. Será fechada automaticamente em 7 dias se não houver atividade. / This issue has been inactive for 60 days. It will be automatically closed in 7 days if there is no activity.'
        close-issue-message: 'Esta issue foi fechada devido à inatividade. / This issue was closed due to inactivity.'
        days-before-issue-stale: 60
        days-before-issue-close: 7
        stale-issue-label: 'stale'
        exempt-issue-labels: 'pinned,security,enhancement'

        # PR settings
        stale-pr-message: 'Este PR está inativo há 30 dias. Será fechado automaticamente em 7 dias se não houver atividade. / This PR has been inactive for 30 days. It will be automatically closed in 7 days if there is no activity.'
        close-pr-message: 'Este PR foi fechado devido à inatividade. / This PR was closed due to inactivity.'
        days-before-pr-stale: 30
        days-before-pr-close: 7
        stale-pr-label: 'stale'
        exempt-pr-labels: 'pinned,security'

        # General settings
        operations-per-run: 50
        remove-stale-when-updated: true
        ascending: true
